### ISSUE TITLE
Already logged in with different provider

### ISSUE THREAD

**Issue by jerauf** [adamwathan/eloquent-oauth#28]
How do you avoid an error with people logging in with different providers? So, if I log in with Github one visit and it creates a user and a oauth identity. Then the next time I visit the site and need to log in, I forgot that I used Github and click 'log in with Facebook'. It throws an error saying that there is a duplicate entry.

**Comment by adamwathan** [comment]
The package itself shouldn't be creating a duplicate entry... Are you perhaps saving the persons email and have your email column set with a unique constraint?

There's no good way to detect when someone logs in with one provider, then later with another. Trying to do it based on e-mail address is a big security vulnerability. See this issue for more details: https://github.com/adamwathan/eloquent-oauth/issues/19

**Comment by jerauf** [comment]
That makes sense. How would I give the user an alert saying "you've signed up with another provider" then?

**Comment by adamwathan** [comment]
If you really wanted to do that I would use the callback on `OAuth::login()` to check if the email is already assigned to another user and throw your own exception that you can catch in the controller and handle however you want.

The reality is though that no one really deals with that problem. With some providers, you'd have no way of telling anyways. For example, the Instagram API does not let you retrieve the user's email address at all, so you have no way of knowing. If you test what you're talking about with a variety of popular sites that support social login, I think you'll find they all just create multiple accounts for you and make no effort to reconcile them.

This is actually a common complaint of sites that support multiple social logins in general :/ It's definitely a trade-off between the convenience of providing multiple login options vs. the risk of the user forgetting which one they chose.

I'm planning to split this package up in the future so that there's one main repo for the bulk of the package logic, and each actual provider is in it's own repo, and you can mix and match the actual ones you need, which I think will help encourage more careful selection of which providers you actually want to support for your application. Similar to how Flysystem is broken up for example.

**Comment by jerauf** [comment]
All right. Great.

Thanks for the help. And thanks for the great package. I was up and running literally in an hour with only this one question.

**Comment by adamwathan** [comment]
No problem happy to help and glad you like the package! :smile: Definitely let me know how it works out for you, would love to improve it however I can based on your feedback.
