### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by cjonstrup** [adamwathan/eloquent-oauth#33]
Hi,

Great package.

I just testet with postgresql 9.4 and I had to change my schema to allow nulls before it was working.

Schema::create('users', function(Blueprint $table)
{
  $table->increments('id');
  $table->string('name')->nullable();
  $table->string('email')->unique()->nullable();
  $table->string('password', 60)->nullable();

I dont know if you can check for this in your code and populate default values for the fillable fields if there are a match.

**Comment by mikebronner** [comment]
Possible solution might be including a migration script in the package? But might be too 'dirty'. :)

**Comment by adamwathan** [comment]
Yeah I think what I need to do is just clearly document that this package expects to be able to create a User object and save it without specifying any fields.

The other option would be to use the closure version of `login` to provide values for any required fields in your users table:

```
OAuth::login('github', function ($user, $userDetails) {
    $user->name = 'whatever';
    $user->email = 'whatever';
    $user->password = 'whatever';
});
```

...but really if you are trying to implement login through an OAuth provider, you need to allow users to exist that don't have email/password credentials, since that's not what they're using to login. So yeah, tricky problem to solve in the package itself :/

I'll definitely update the documentation to be more clear about this, just need to figure out the best way to add it in to make it easy to notice.

Thanks!
