### ISSUE TITLE
Error login with multiple providers

### ISSUE THREAD

**Issue by anvarstudios** [adamwathan/eloquent-oauth#42]
Good night,
It is possible that a user can install one or more providers and start with one section. This will create a new field in the users table.

My email is register with facebook avasquez22@misena.edu.co and new test with github have  next error.

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'avasquez22@misena.edu.co' for key 'users_email_unique' (SQL: insert into `users` (`email`, `name`, `updated_at`, `created_at`) values (avasquez22@misena.edu.co, Andres Felipe Vasquez, 2015-03-12 02:55:56, 2015-03-12 02:55:56))

**Comment by anvarstudios** [comment]
Hello, Is there any way you can have two suppliers for the same user?

**Comment by adamwathan** [comment]
Hey, unfortunately this isn't supported automatically yet. It's also not a good idea to rely on the email address provided by Facebook/GitHub to determine if two users are the same.

More details on that here: https://github.com/adamwathan/eloquent-oauth/issues/19

It sounds like you are saving the email like this, yeah?

```
OAuth::login('github', function ($user, $details) {
    $user->email = $details->email;
    $user->save();
});
```
Since you can't guarantee uniqueness of emails from third-parties and you can't guarantee two third party users are really the same user based on email, you either need to remove the unique constraint (guessing this is not an option and you are providing email/password login as well) or save the email to a different column or table. Maybe a `contact_email` column that has no unique constraint.

Then implement a mutator on your `User` class that looks something like:

```
public function getEmailAttribute()
{
    return $this->attributes['email'] ?: $this->attributes['contact_email'];
}
```
...or check the `oauth_identities` table explicitly if you'd like to confirm the user definitely came from a third party source and their email is stored somewhere else.

**Comment by dhruba-sarma** [comment]
A simple solution might help others.....

In core package root directory Authenticator.php  return the user in callback like bellow

if ($callback) {
      $user = $callback($user, $userDetails); // $callback($user, $userDetails);
}

and in your application

OAuth::login($provider, function ($user, $details) {
    
    $exist = User::where('email', $details->email)->first();
    if($exist){
     $user = $exist;
    }
    $user->email = $details->email;
   return $user;
});

pn: $provider (facebook, google, or github)

**Comment by adamwathan** [comment]
@dhruba-sarma Yeah I was thinking that as well, great idea. Going to get that in the next release.
