### ISSUE TITLE
Error login with instagram

### ISSUE THREAD

**Issue by anvarstudios** [adamwathan/eloquent-oauth#63]
I have a problem is when it comes redirects from instagram no data to store in the database.

No abut the error so that it can solve

```sql
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `users` (`email`, `name`, `updated_at`, `created_at`) values (, , 2015-04-21 02:42:40, 2015-04-21 02:42:40))
```

**Comment by adamwathan** [comment]
Hey, the problem is your `users` table contains columns that are either not nullable or don't have default values.

I need to expand on this in the docs, but this package will try to create a User when someone logs in, so your `users` table needs to be designed to accommodate that, since now that all of your users will have email/password since they are logging in with a third party provider.
