### ISSUE TITLE
EloquentOAuthServiceProvider.php missing in master branch

### ISSUE THREAD

**Issue by jsm9153** [adamwathan/eloquent-oauth#67]
If you follow the installation instructions the file EloquentOAuthServiceProvider.php (and several others) are not included which make following the remainder of the installation impossible.

I had to manually set the branch to "dev-laravel-5" in order to pull in the updated branch with the required files.

**Comment by adamwathan** [comment]
If you use version `~5.0` you should be ok. Version 6+ includes no installation/config stuff, because it's been pulled out into these wrapper packages:

http://github.com/adamwathan/eloquent-oauth-l5
http://github.com/adamwathan/eloquent-oauth-l4

I'd recommend just using the new [Laravel 5 wrapper](http://github.com/adamwathan/eloquent-oauth-l5) since that's what will be maintained going forward.

I needed to split everything up because it was getting complicated to support both Laravel 4 and 5 from the same package :(
