### ISSUE TITLE
Seems to be incompatible with Laravel 5.1

### ISSUE THREAD

**Issue by kaju74** [adamwathan/eloquent-oauth#71]
I've tryed to update my Laravel installation to 5.1 and got the following errors:

- Conclusion: don't install laravel/framework v5.1.1
    - Conclusion: don't install laravel/framework v5.1.0
    - adamwathan/eloquent-oauth v5.0.3 requires illuminate/support 5.0.* -> satisfiable by laravel/framework[v5.0.33], illuminate/support[5.0.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].

How to solve this?

Thank you,
...

**Comment by adamwathan** [comment]
I'm way behind on updating the docs for this but try using this package instead:

https://github.com/adamwathan/eloquent-oauth-l5

I broke out Laravel 4 and Laravel 5 support into separate wrapper packages because the package asset publishing changed so much between 4 and 5 and it was hard to maintain in a single package.

I'll try and get the docs updated within a couple of days, thanks for reminding me.
