### ISSUE TITLE
Support for twitter?

### ISSUE THREAD

**Issue by bsheikh** [adamwathan/eloquent-oauth#77]
Is it possible to add Twitter support?

**Comment by bsheikh** [comment]
realized this should be posted in oath-l5

**Comment by adamwathan** [comment]
Nah it's fine to post it here, this is the main repo, the L5 one is just a light wrapper with a service provider.

I'd like to add Twitter support but haven't had time myself. It's a bit more complicated than others since they only support OAuth 1.0 and I haven't written any providers for that protocol, but with any luck it's doable. Happy to accept PRs :)

**Comment by iplayguitar81** [comment]
i agree this is such a cool/sleek solution.  I appreciate it!  I agree that it would be nice to see this functionality in the future!
