### ISSUE TITLE
Request FACEBOOK basic data (gender, user_friends)

### ISSUE THREAD

**Issue by rbkkbr** [adamwathan/eloquent-oauth#80]
I have the keys in scope => ['public_profile', 'user_friends']
but in
SocialAuth::login('facebook', function($user, $details) {
			dd($details->raw());
});
I had this:
array:7 [▼
  "email" => "xxx@xxx.com"
  "name" => "Aaa Bbb"
  "first_name" => "Aaa"
  "last_name" => "Bbb"
  "age_range" => array:1 [▼
    "min" => 21
  ]
  "timezone" => -2
  "id" => "10223321332389"
]

where I can get gender??? and friends list??

**Comment by adamwathan** [comment]
If you look here: https://developers.facebook.com/docs/graph-api/reference/v2.2/user

...you'll see gender is omitted if it is set to a custom value, so that is probably the case here.

You can no longer retrieve someone's friends list through the API as of v2.0, details here: https://developers.facebook.com/docs/apps/faq#friends_list

That info would not come back as part of the `user` endpoint regardless, you would need to make a separate call to the API for that.
