### ISSUE TITLE
Adding a 'remember' parameter to login() method

### ISSUE THREAD

**Issue by dusterio** [adamwathan/eloquent-oauth#82]
I think it could be useful to be able to pass 'remember' parameter to underlying Auth implementation, eg:

```
    public function login($providerAlias, $userDetails, $remember = false, $callback = null)
    {
        $user = $this->getUser($providerAlias, $userDetails);
        $user = $this->runCallback($callback, $user, $userDetails);
        $this->updateUser($user, $providerAlias, $userDetails);
        $this->auth->login($user, $remember);
    }
```

It may not sound critical, but it's kind of annoying that you have to log in every day. It's quite a common web practice today to remember logged in users for a while!

**Comment by adamwathan** [comment]
Yeah I agree, originally I was hesitant to do this because short logins was a good way to make sure the access token in the DB was always recent, and not having to worry about refresh tokens and stuff. But I think ultimately I'd prefer to not store the token at all, since this package never uses it after login anyways, and if people want to keep a copy of the token they can save it elsewhere in the login callback. Will definitely get the remember stuff in.
